version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
  pre_build:
    commands:
      - echo Create new lambda function archive file...
      - zip lambda.zip *  -r -x .git/\* \*.sh \*.yml tests/\* node_modules/aws-sdk/\* \*.zip
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image for $IMAGE_REPO_NAME...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image for $IMAGE_REPO_NAME...
artifacts:
  files:
    - imagedefinitions.json
