version: 0.2

phases:
  install:
    commands:
      - echo Install package of lambda function..
      - chmod 777 ./lambda_deploy.sh
  build:
    commands:
      - echo Deploy lambda started on `date` 
      - ./lambda_deploy.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - imagedefinitions.json
